# Generated by Django 4.0.4 on 2022-06-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
