# Generated by Django 4.0.4 on 2022-06-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_remove_post_topic_post_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_tutorial',
            field=models.URLField(null=True),
        ),
    ]
